name: Build

on:
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches-ignore:
      - 'master'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'corretto'
      - name: Run mvn compile
        run: mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn compile
      - name: Run mvn test
        run: mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn test
      - name: Run mvn checkstyle check
        run: mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn checkstyle:check
    